"\n"
	"Usage: rtpdecode.bin [options]\n"
"-h help\n"
"-d debug on\n"
"-l local recv port(default:8888)\n"
"-s video sps info(base64)\n"
"-p video pps info(base64)\n"
"\n"
"For example:\n"
"    ./rtpdecode.bin -d -l 5004 -s J01AKakYDwBE/LgDUBAQG2wrXvfAQA== -p KN4JyA==\n"
"\n"
"control key:\n"
"    a           set alpha\n"
"    b           set alpha\n"
"    c           set rect\n"
"    d           set rect\n"
"    q           exit\n"
"\n"
